### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by artinboghosian**
Issues running tests using 2.2 with OpenSSL, so i upgraded to 2.3 which is version of Ruby used in main app.

### CODE REVIEW

**Comment by artinboghosian** [comment]
Testing

**Comment by artinboghosian** [comment]
Testing again

**Comment by artinboghosian** [comment]
Please merge this when you get a chance @StephenRoos.

**Review by StephenRoos — APPROVED** [review]
:+1:

**Pull request merged**
